# JetifyTransform + Kotlin kompilyatsiyasi uchun 1536M yetmaydi:
# "Java heap space" xatosi bilan build to'xtayotgan edi.
org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=512M
android.useAndroidX=true
android.enableJetifier=true
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.auto-download=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
